// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: campaign.sql

package sqlc_generated

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCampaign = `-- name: CreateCampaign :one
INSERT INTO campaigns (name)
VALUES ($1)
RETURNING id, name, created_at
`

func (q *Queries) CreateCampaign(ctx context.Context, name string) (Campaign, error) {
	row := q.db.QueryRow(ctx, createCampaign, name)
	var i Campaign
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const deleteCampaign = `-- name: DeleteCampaign :exec
DELETE FROM campaigns
WHERE id = $1
`

func (q *Queries) DeleteCampaign(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCampaign, id)
	return err
}

const getAllCampaigns = `-- name: GetAllCampaigns :many
SELECT id, name, created_at FROM campaigns
`

func (q *Queries) GetAllCampaigns(ctx context.Context) ([]Campaign, error) {
	rows, err := q.db.Query(ctx, getAllCampaigns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Campaign
	for rows.Next() {
		var i Campaign
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCampaign = `-- name: GetCampaign :one
SELECT id, name, created_at FROM campaigns
WHERE id = $1
`

func (q *Queries) GetCampaign(ctx context.Context, id pgtype.UUID) (Campaign, error) {
	row := q.db.QueryRow(ctx, getCampaign, id)
	var i Campaign
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}
