// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: channels.sql

package sqlc_generated

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createChannel = `-- name: CreateChannel :one
INSERT INTO channels (topic_id, type, config, template)
VALUES ($1, $2, $3, $4)
RETURNING id, topic_id, type, config, template, created_at
`

type CreateChannelParams struct {
	TopicID  pgtype.UUID `json:"topic_id"`
	Type     string      `json:"type"`
	Config   []byte      `json:"config"`
	Template string      `json:"template"`
}

func (q *Queries) CreateChannel(ctx context.Context, arg CreateChannelParams) (Channel, error) {
	row := q.db.QueryRow(ctx, createChannel,
		arg.TopicID,
		arg.Type,
		arg.Config,
		arg.Template,
	)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.TopicID,
		&i.Type,
		&i.Config,
		&i.Template,
		&i.CreatedAt,
	)
	return i, err
}

const getChannelsByTopicID = `-- name: GetChannelsByTopicID :many
SELECT id, topic_id, type, config, template, created_at FROM channels
WHERE topic_id = $1
`

func (q *Queries) GetChannelsByTopicID(ctx context.Context, topicID pgtype.UUID) ([]Channel, error) {
	rows, err := q.db.Query(ctx, getChannelsByTopicID, topicID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Channel
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.ID,
			&i.TopicID,
			&i.Type,
			&i.Config,
			&i.Template,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
