// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc_generated

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Channel struct {
	ID        pgtype.UUID        `json:"id"`
	TopicID   pgtype.UUID        `json:"topic_id"`
	Type      string             `json:"type"`
	Config    []byte             `json:"config"`
	Template  string             `json:"template"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Topic struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	Description pgtype.Text        `json:"description"`
}
