// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc_generated

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateChannel(ctx context.Context, arg CreateChannelParams) (Channel, error)
	CreateTopic(ctx context.Context, arg CreateTopicParams) (Topic, error)
	DeleteTopic(ctx context.Context, id pgtype.UUID) error
	GetAllTopics(ctx context.Context) ([]Topic, error)
	GetChannelsByTopicID(ctx context.Context, topicID pgtype.UUID) ([]Channel, error)
	GetTopic(ctx context.Context, id pgtype.UUID) (Topic, error)
	UpdateTopic(ctx context.Context, arg UpdateTopicParams) (Topic, error)
}

var _ Querier = (*Queries)(nil)
