// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc_generated

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateCampaign(ctx context.Context, name string) (Campaign, error)
	CreateChannel(ctx context.Context, arg CreateChannelParams) (Channel, error)
	GetAllCampaign(ctx context.Context) ([]Campaign, error)
	GetCampaign(ctx context.Context, id pgtype.UUID) (Campaign, error)
	GetChannelsByCampaignID(ctx context.Context, campaignID pgtype.UUID) ([]Channel, error)
}

var _ Querier = (*Queries)(nil)
