// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: topic.sql

package sqlc_generated

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTopic = `-- name: CreateTopic :one
INSERT INTO topics (name, description)
VALUES ($1, $2)
RETURNING id, name, created_at, description
`

type CreateTopicParams struct {
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) CreateTopic(ctx context.Context, arg CreateTopicParams) (Topic, error) {
	row := q.db.QueryRow(ctx, createTopic, arg.Name, arg.Description)
	var i Topic
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.Description,
	)
	return i, err
}

const deleteTopic = `-- name: DeleteTopic :exec
DELETE FROM topics
WHERE id = $1
`

func (q *Queries) DeleteTopic(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTopic, id)
	return err
}

const getAllTopics = `-- name: GetAllTopics :many
SELECT id, name, created_at, description FROM topics
`

func (q *Queries) GetAllTopics(ctx context.Context) ([]Topic, error) {
	rows, err := q.db.Query(ctx, getAllTopics)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Topic
	for rows.Next() {
		var i Topic
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopic = `-- name: GetTopic :one
SELECT id, name, created_at, description FROM topics
WHERE id = $1
`

func (q *Queries) GetTopic(ctx context.Context, id pgtype.UUID) (Topic, error) {
	row := q.db.QueryRow(ctx, getTopic, id)
	var i Topic
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.Description,
	)
	return i, err
}

const updateTopic = `-- name: UpdateTopic :one
UPDATE topics
SET
  name = $1,
  description = $2
WHERE
  id = $3
RETURNING id, name, created_at, description
`

type UpdateTopicParams struct {
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	ID          pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateTopic(ctx context.Context, arg UpdateTopicParams) (Topic, error) {
	row := q.db.QueryRow(ctx, updateTopic, arg.Name, arg.Description, arg.ID)
	var i Topic
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.Description,
	)
	return i, err
}
